// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EnemyBook","status":false,"description":"Displays detailed statuses of enemies.","parameters":{"Unknown Data":"??????"}},
{"name":"Test","status":true,"description":"test","parameters":{}}
];
